#!/bin/sh
#
# MikoPBX - free phone system for small business
# Copyright © 2017-2021 Alexey Portnov and Nikolay Beketov
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <https://www.gnu.org/licenses/>.
#

/sbin/syslogd -S -C512
HOME=/;
PATH=/sbin:/bin:/usr/sbin:/usr/bin;
export HOME PATH;

if [ ! '5' = "$(uname -r | cut -d '.' -f 1)" ]; then
  echo 'Only the kernel version 5 is supported';
  exit 5;
fi;

if [ ! -f /cf/conf/mikopbx.db ]; then
  mkdir -p /cf/conf;
  cp /conf.default/mikopbx.db /cf/conf/mikopbx.db;
fi;

/etc/rc/bootup 2>/dev/null;
/etc/rc/bootup_pbx 2>/dev/null;
/bin/tail -f /dev/null;