#!/bin/sh

kernelVersion="$(/bin/uname -r | /bin/cut -f 1 -d '.')";

if [ ! "$kernelVersion" = '5' ]; then
  echo 'ERROR: Only linux 5 is supported...';
  exit 4;
fi

cleanup()
{
  echoToTeletype "Receive signal to restart "...;
  /sbin/freestorage 'doNotUnMount';
  /sbin/freeupoffload;
  sleep 4;
  exit 0;
}
. /sbin/shell_functions.sh;
exec </dev/console >/dev/console 2>/dev/console;
echoToTeletype;

for sig in SIGINT SIGTERM SIGHUP SIGQUIT EXIT; do
  trap cleanup "$sig";
done

php -f /sbin/Entrypoint.php &

while true; do sleep 1; done