#!/bin/sh

cleanup()
{
  echoToTeletype "Receive signal to restart "...;
  /sbin/freestorage 'doNotUnMount';
  /sbin/freeupoffload;
  sleep 4;
  exit 0;
}
. /sbin/shell_functions.sh;
exec </dev/console >/dev/console 2>/dev/console;
echoToTeletype;

for sig in SIGINT SIGTERM SIGHUP SIGQUIT EXIT; do
  trap cleanup "$sig";
done

php -f /sbin/Entrypoint.php &

while true; do sleep 1; done