#!/bin/sh
#
# MikoPBX - free phone system for small business
# Copyright © 2017-2022 Alexey Portnov and Nikolay Beketov
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <https://www.gnu.org/licenses/>.
#

mntPoint="$(/bin/busybox grep "mediaMountPoint" < /etc/inc/mikopbx-settings.json | /bin/busybox cut -f 4 -d '"')";
dbPath="$(/bin/busybox grep "mikopbx.db" < /etc/inc/mikopbx-settings.json | /bin/busybox cut -f 4 -d '"')";
backupDir="${mntPoint}/mikopbx/backup/db"
mkdir -p "$backupDir";

md5="$(/usr/bin/sqlite3 "$dbPath" .dump | /bin/gzip -c | /usr/bin/md5sum | cut -f 1 -d ' ')" ;

/usr/bin/md5sum /storage/usbdisk1/mikopbx/backup/db/*_mikopbx.db.gz | /bin/busybox grep "$md5"> /dev/null 2> /dev/null
result="$?"
if [ "$result" = "1" ];then
  /usr/bin/sqlite3 "$dbPath" .dump | /bin/gzip -c > "$backupDir/$(date '+%Y-%m-%d_h%H_m%M_s%S')_mikopbx.db.gz"
fi;
(
  cd "$backupDir" || exit;
  /bin/busybox ls -1tr | /bin/busybox head -n-5 | /bin/xargs /bin/busybox rm 2> /dev/null
)
