#!/bin/sh

PATH=/sbin:/bin:/usr/bin:/usr/sbin
export PATH

if [ -f /sbin/shell_functions.sh ]; then
. /sbin/shell_functions.sh;
fi

storage='/storage/usbdisk1';

file_storage_device='/var/etc/storage_device';
if [ -f "$file_storage_device" ] ; then
    storage=$(cat "$file_storage_device");
fi;

# killing processes
killprocess_by_name 'cron' -KILL 0;
killprocess_by_name 'safe_asterisk' -KILL 0;
killprocess_by_name 'pdnsd' -KILL 0;
killprocesses '/sbin/monitord' -KILL 1;
killprocesses "$storage" -TERM 3;
killprocesses "$storage" -KILL 1;

# umount  swap
freeSwapByName "$storage";

f_umount "$storage";