#!/bin/sh
#
# MikoPBX - free phone system for small business
# Copyright (C) 2017-2020 Alexey Portnov and Nikolay Beketov
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <https://www.gnu.org/licenses/>.
#

PATH=/sbin:/bin
export PATH

# Подключаем библиотеку функций.
if [ -f /sbin/shell_functions.sh ]; then
. /sbin/shell_functions.sh;
fi

/bin/touch /tmp/freeoffload;

killprocess_by_name 'pdnsd' -9 0;

killprocess_by_name 'crond' -KILL 0;
killprocess_by_name 'nginx' -KILL 0;
killprocess_by_name 'monitord' -KILL 1;

killprocesses '/offload' -TERM 3;
killprocesses '/offload' -KILL 0;

echo " |   - unmounting /offload ...";
f_umount /offload;
echo " |   - unmounting /cf...";
f_umount /cf;

