#!/bin/sh
#
# MikoPBX - free phone system for small business
# Copyright (C) 2017-2020 Alexey Portnov and Nikolay Beketov
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <https://www.gnu.org/licenses/>.
#
/sbin/syslogd -S -C512

HOME=/;
PATH=/sbin:/bin:/usr/sbin:/usr/bin;

export HOME PATH;
echo 'Create system dirs';
# Создание каталогов и ссылок.
mkdir -p /dev/pts \
		 /dev/bus\
		 /tmp \
		 /ultmp \
		 /offload \
		 /cf/conf \
		 /var/etc \
		 /var/spool/cron \
		 /var/spool/cron/crontabs \
		 /var/lib/php/session;

chmod 777 /tmp				 
ln -s /offload/rootfs/usr /usr;
ln -s /sys/bus/usb /dev/bus/usb

rm -rf /dev/null;
mknod /dev/null c 1 3;
mknod /dev/initctl p;

# Подключаем устройства.
/sbin/udevd --daemon;
/sbin/udevadm trigger;
/sbin/udevadm settle;

sleep 5;
mount -t devpts -o gid=5,mode=620 devpts /dev/pts;

/bin/busybox ifconfig lo 127.0.0.1
# Опции ядра linux
/sbin/sysctl -w kernel.printk="3 4 1 6" > /dev/null 2> /dev/null;
/sbin/sysctl -w net.ipv6.conf.all.disable_ipv6=1 > /dev/null 2> /dev/null;
/sbin/sysctl vm.overcommit_memory=1 > /dev/null 2> /dev/null;
/sbin/sysctl net.core.somaxconn=65535 > /dev/null 2> /dev/null;

# RAID
mdadmPath=$(/sbin/which mdadm);
if [ -n "$mdadmPath" ]; then
  "$mdadmPath" --detail   --scan | /bin/busybox cut -d ' ' -f 2 | /bin/xargs "$mdadmPath" --stop > /dev/null 2> /dev/null;
  "$mdadmPath" --assemble --scan;
fi;
# RAID END

echo;
echo " - Start /sbin/mountoffload...";
/sbin/mountoffload;
echo " - Start /etc/rc/mountconfdir...";
/etc/rc/mountconfdir;

/etc/rc/bootup 2> /dev/null