#!/bin/sh
#
# MikoPBX - free phone system for small business
# Copyright (C) 2017-2020 Alexey Portnov and Nikolay Beketov
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <https://www.gnu.org/licenses/>.
#

/sbin/freestorage;
/sbin/freeupoffload;

# RAID
mdadmPath=$(/sbin/which mdadm);
if [ -n "$mdadmPath" ]; then
  "$mdadmPath" --detail   --scan | /bin/busybox cut -d ' ' -f 2 | /bin/xargs "$mdadmPath" --stop > /dev/null 2> /dev/null;
fi;
# RAID END

if [ -f /tmp/ejectcd ]; then
    # Попробуем изъять диск.
    cddev=$(/sbin/sysctl -n dev.cdrom.info | /bin/busybox grep "drive name" | /bin/busybox cut -f 3)
    echo "Eject CD from drive ${cddev}...";
    /bin/busybox eject "/dev/${cddev}" 2>&1 > /dev/null
    result="$?";
    if [ ! "$result" = '0' ]; then
      /bin/busybox eject -s "/dev/${cddev}" 2>&1 > /dev/null;
    fi;
else
    sleep 3;
fi

/sbin/reboot
