#!/bin/sh
#
# MikoPBX - free phone system for small business
# Copyright (C) 2017-2020 Alexey Portnov and Nikolay Beketov
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <https://www.gnu.org/licenses/>.
#

case $1 in
enable)
  #/sbin/mdmfs -s 20m md1 /ultmp > /dev/null 2>&1
  ;;

recover_upgrade)
  # $2 firmware image
  # $3 device
  cd /
  sleep 5
  exec </dev/console >/dev/console 2>/dev/console
  echo
  echo " - Firmware upgrade in progress..."
  echo " - backing up configuration..."
  mkdir -p /tmp/configbak
  img_file="$2"
  if [ -f /offload/livecd ]; then
    /bin/busybox cp -p /conf.recover/conf/* /tmp/configbak
    echo " - unmounting /conf.recover..."
    /bin/umount -f /conf.recover
  else
    /bin/busybox cp -R /cf/conf/* /tmp/configbak

    mounted_storage=$(mount | /bin/busybox grep storage | /bin/busybox awk '{ print $1}')
    # Получаем имя 4ого раздела (если он есть)
    partition4Name=$(/bin/lsblk -r | /bin/busybox grep "$(/bin/busybox basename "$(cat /var/etc/cfdevice)")" | /bin/busybox cut -d ' ' -f 1 | /bin/busybox grep "4$" | /bin/busybox sort -u)
    if [ "/dev/${partition4Name}" != "${mounted_storage}" ]; then
      # Storage на отдельном диске.
      img_file="$2"
    else
      # Storage на диске основном диске,
      # так как его нужно отмнонтировать, то перемещамем образ в RAM.
      echo " - move img to RAM ..."
      tmp_img=$(basename "$2")
      img_file="/tmp/${tmp_img}"
      # Перемещаем img файл в /tmp. Storage будет отмонтирован.
      src_file=$(readlink -f "$2")
      if [ "${src_file}" != "${img_file}" ]; then
        mv "${src_file}" "${img_file}"
      fi

      echo " - free storage ..."
      /sbin/freestorage
    fi
    # Отключаем основной диск.
    /sbin/freeupoffload
  fi

  echo " - installing image..."
  if [ -r "${img_file}" ]; then
    /bin/pv -p "${img_file}" | /bin/gunzip | dd of="$3" bs=512 >/dev/null 2>&1
    echo " - dd end working..."
    # Обновляем таблицу разделов.
    /sbin/initial.storage.part.four create "$3"
    echo " - disk part four result ${?}..."
  fi
  /sbin/blockdev --rereadpt "$3" >/dev/null 2>&1
  sleep 3

  partition3Name=$(/bin/lsblk -r | /bin/busybox grep "$(/bin/busybox basename "$3")" | /bin/busybox cut -d ' ' -f 1 | /bin/busybox grep "3$" | /bin/busybox sort -u)
  if [ -f /offload/livecd ]; then
    echo " - re-mounting /conf.recover read/write..."
    /bin/mount -w -o noatime "/dev/${partition3Name}" /conf.recover
    rm -f /conf.recover/conf/*
    echo " - restoring configuration"
    /bin/busybox cp -p /tmp/configbak/* /conf.recover/conf/
    touch /tmp/ejectcd
  else
    /bin/mount -w -o noatime "/dev/${partition3Name}" /cf/
    /bin/busybox cp /tmp/configbak/* /cf/conf/
    rm -rf "${img_file}"
  fi

  echo " - rebooting system..."
  /sbin/mikopbx_reboot
  ;;
esac
