#!/bin/sh
#
# MikoPBX - free phone system for small business
# Copyright (C) 2017-2023 Alexey Portnov and Nikolay Beketov
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <https://www.gnu.org/licenses/>.
#
. /sbin/shell_functions.sh;
img_file="$1";
device="$2"

exec </dev/console >/dev/console 2>/dev/console;
echoToTeletype;
echoToTeletype " - Firmware upgrade in progress...";
echoToTeletype " - backing up configuration...";
mkdir -p /tmp/configbak;

md5Hash="$(/bin/gunzip -N -l < "${img_file}" | /bin/busybox grep -v uncompressed_name | /bin/busybox awk  '{ print $4}')";
if [ "$md5Hash" != "$(/bin/gunzip -c "${img_file}" |/bin/busybox md5sum | /bin/busybox cut -f 1 -d ' ')" ] ; then
    echoToTeletype " - The checksum of the system image does not match.";
    echoToTeletype " - Update aborted...";
    rm -rf "$img_file";
    sleep 3;
    /sbin/pbx_reboot;
else
    echoToTeletype " - Successful checksum verification";
fi

if [ -f /offload/livecd ]; then
  /bin/busybox cp -p /conf.recover/conf/* /tmp/configbak;
  echoToTeletype " - unmounting /conf.recover...";
  /bin/umount -f /conf.recover;
else
  /bin/busybox cp -R /cf/conf/* /tmp/configbak;

  mounted_storage=$(mount | /bin/busybox grep storage | /bin/busybox awk '{ print $1}');
  # Получаем имя 4ого раздела (если он есть)
  partition4Name=$(/bin/lsblk -r | /bin/busybox grep "$(/bin/busybox basename "$(cat /var/etc/cfdevice)")" | /bin/busybox cut -d ' ' -f 1 | /bin/busybox grep "4$" | /bin/busybox sort -u)
  if [ "/dev/${partition4Name}" != "${mounted_storage}" ]; then
    # Storage на отдельном диске.
    echoToTeletype " - free storage ...";
    /sbin/freestorage "doNotUnMount";

    backupDir="$(cat /var/etc/storage_device)/mikopbx/backup/last-update-firmware"
    backupImg="$backupDir/system.img";
    rm -rf "$backupDir"; mkdir -p "$backupDir";

    echoToTeletype " - copy conf to storage ...";
    /bin/busybox cp -R /cf/conf/* "$backupDir";

    echoToTeletype " - backup system img to storage ...";
    /bin/pv -p "/dev/$(/bin/busybox basename "$(cat /var/etc/cfdevice)")" | /bin/gzip | dd of="$backupImg" bs=512 >/dev/null 2>&1;
  else
    # Storage на диске основном диске,
    # так как его нужно отмнонтировать, то перемещамем образ в RAM.
    echoToTeletype " - move img to RAM ..."
    tmp_img=$(/bin/busybox basename "$1");
    img_file="/tmp/${tmp_img}";
    # Перемещаем img файл в /tmp. Storage будет отмонтирован.
    src_file=$(/bin/readlink -f "$1")
    if [ "${src_file}" != "${img_file}" ]; then
      mv "${src_file}" "${img_file}";
    fi

    echoToTeletype " - free storage ...";
    /sbin/freestorage;
  fi

  # Отключаем основной диск.
  /sbin/freeupoffload;
fi

echoToTeletype " - installing image..."
if [ -r "${img_file}" ]; then
  /bin/pv -p "${img_file}" | /bin/gunzip | dd of="$device" bs=512 >/dev/null 2>&1;
  resultPv="$?";
  if [ ! "$resultPv" = '0' ] || [ ! "$(/sbin/parted --script --align optimal "${device}" "print" | grep primary | /bin/busybox wc -l)" = '3' ]; then
    if [ -f "$backupImg" ]; then
      /bin/pv -p "$backupImg" | /bin/gunzip | dd of="$device" bs=512 >/dev/null 2>&1;
    fi;
  fi;
  rm -rf "$backupImg";
  echoToTeletype " - dd end working...";
  # Обновляем таблицу разделов.
  /sbin/initial.storage.part.four create "$device";
  echoToTeletype " - disk part four result ${?}...";
fi
/sbin/blockdev --rereadpt "$device" > /dev/null 2>&1
sleep 3;

partition3Name=$(/bin/lsblk -r -p | /bin/busybox grep "$(/bin/busybox basename "$device")" | /bin/busybox cut -d ' ' -f 1 | /bin/busybox grep "3$" | /bin/busybox sort -u)
if [ -f /offload/livecd ]; then
  echoToTeletype " - re-mounting /conf.recover read/write..."
  /bin/mount -w -o noatime "${partition3Name}" /conf.recover
  rm -f /conf.recover/conf/*
  echoToTeletype " - restoring configuration"
  /bin/busybox cp -p /tmp/configbak/* /conf.recover/conf/
  touch /tmp/ejectcd

  echoToTeletype " - rebooting system..."
  /sbin/pbx_reboot;
else
  echo " - conf partition: ${partition3Name}";
  /bin/busybox yes | /sbin/mkfs.ext4 "${partition3Name}" > /dev/null 2> /dev/null;
  /bin/mount -w -o noatime "${partition3Name}" /cf/
  mkdir -p /cf/conf/;
  /bin/busybox cp /tmp/configbak/* /cf/conf/;
  rm -rf "${img_file}";
fi