<?php
/**
 * REST API translations for OpenAPI documentation (English)
 * These translations are used in REST API controllers and OpenAPI specification generation
 */

return [

    // ============================================================================
    // API Resource Descriptions (unified for API and UI empty state placeholders)
    // ============================================================================
    'rest_Advice_ApiDescription' => 'System advice and notification management for PBX health monitoring. Provides automated analysis of system configuration, security recommendations, performance warnings, and best practice suggestions. This is a read-only resource with custom methods for retrieving and refreshing system advice.',
    'rest_ApiKeys_ApiDescription' => 'Comprehensive API keys management for secure REST API access. Features include JWT token generation, permission management, endpoint restrictions, network filtering, and key lifecycle management. API keys provide secure programmatic access to the PBX REST API with fine-grained access control.',
    'rest_AsteriskManagers_ApiDescription' => 'Asterisk Manager Interface (AMI) user management for PBX administration. AMI users provide programmatic access to Asterisk for monitoring, control, and integration. Features include permission management, secure authentication, and administrative access controls.',
    'rest_AsteriskRestUsers_ApiDescription' => 'Comprehensive Asterisk REST Interface (ARI) user management for real-time call control. ARI provides WebSocket-based APIs for building custom telephony applications with full call control capabilities. Features include user authentication, application binding, and permission management for ARI applications.',
    'rest_Auth_ApiDescription' => 'JWT-based authentication system with refresh tokens for REST API clients and SPA applications. Supports password authentication and passkey (WebAuthn) authentication. Returns short-lived access tokens (JWT, 15 minutes) and long-lived refresh tokens (httpOnly cookie, 30 days). Implements automatic token rotation and device tracking for enhanced security.',
    'rest_CallQueues_ApiDescription' => 'Comprehensive call queue management for advanced call distribution. Features include multiple distribution strategies (ring-all, round-robin, linear, random, least-recent), member management with priority/penalty settings, announcement configuration, timeout handling, and automatic call routing.',
    'rest_Cdr_ApiDescription' => 'Comprehensive Call Detail Records (CDR) management for call history analysis and reporting. Provides read-only access to completed call records, real-time monitoring of active calls and channels, and streaming playback of call recordings with HTTP range support. Features advanced filtering by date, caller/callee, duration, and call status.',
    'rest_ConferenceRooms_ApiDescription' => 'Conference room management for multi-party audio conferencing.',
    'rest_CustomFiles_ApiDescription' => 'Comprehensive custom files management for system configuration customization. Allows managing custom configuration files that are automatically restored after system updates. Supports multiple modes: override (replace file), append (add content), script (executable). Content is stored as base64-encoded strings for binary safety.',
    'rest_DialplanApplications_ApiDescription' => 'Dialplan application management for custom call handling logic and features.',
    'rest_Employees_ApiDescription' => 'Comprehensive employee management for PBX users. Employees represent staff members with extension numbers, user accounts, and SIP credentials.',
    'rest_Extensions_ApiDescription' => 'Comprehensive extensions management for all PBX extension numbers. Extensions are created through various entities (Employees, IVR menus, Queues, etc.). This API provides unified access to list, search, and manage all extension numbers with type information and availability checking.',
    'rest_Fail2Ban_ApiDescription' => 'Comprehensive Fail2Ban intrusion prevention management. Provides singleton REST operations for configuring ban policies, timeouts, and IP whitelists. Automatically blocks malicious IP addresses after detecting repeated failed authentication attempts.',
    'rest_Files_ApiDescription' => 'Comprehensive file management operations. Provides REST operations for reading, uploading, and deleting files, plus custom methods for chunked uploads and firmware downloads. Supports both simple PUT uploads and resumable chunked uploads via Resumable.js protocol.',
    'rest_Firewall_ApiDescription' => 'Comprehensive firewall rule management. Provides full CRUD operations for network access control rules, plus custom methods for managing banned IPs, enabling/disabling firewall, and retrieving default configurations.',
    'rest_GeneralSettings_ApiDescription' => 'Comprehensive system-wide configuration management. Provides access to PBX general settings including system name, language, timezone, web/SSH access configuration, SIP settings, recording options, and codec management. Implements singleton resource pattern.',
    'rest_Iax_ApiDescription' => 'IAX (Inter-Asterisk eXchange) protocol management for VoIP trunk provider connections. Provides real-time monitoring of IAX provider registration status, peer connectivity states, and response times for IAX-based SIP trunks.',
    'rest_IaxProviders_ApiDescription' => 'Comprehensive IAX provider management for Internet Asterisk eXchange (IAX) protocol trunking. IAX is a VoIP protocol designed for efficient trunk connections between Asterisk servers. Features include provider registration, status monitoring, connection testing, and statistics tracking.',
    'rest_IncomingRoutes_ApiDescription' => 'Comprehensive incoming route management for call routing and DID number handling. Features include provider-based routing, number pattern matching, priority management, timeout configuration, extension forwarding, and audio message playback.',
    'rest_IvrMenu_ApiDescription' => 'Comprehensive IVR menu management for automated call routing and self-service. Features include customizable menu options, timeout handling, audio file assignments, digit-based navigation, and flexible routing rules for creating sophisticated automated attendant systems.',
    'rest_License_ApiDescription' => 'License management for MikoPBX system. Features include license activation, validation, key management, feature capture for products, metrics reporting, and license server connectivity checks.',
    'rest_MailSettings_ApiDescription' => 'Mail server configuration management for system notifications and alerts. Supports SMTP authentication including OAuth2 for Gmail, Outlook, and other providers. Includes connection testing and automated token refresh capabilities.',
    'rest_Modules_ApiDescription' => 'Comprehensive extension modules management for PBX functionality extension. Features include module installation from repository or package, updates, enable/disable operations, metadata retrieval, and automatic dependency handling.',
    'rest_Network_ApiDescription' => 'Network configuration management for MikoPBX system. Features include network interface management (Ethernet, VLAN), IP address configuration (DHCP, Static), gateway settings, DNS configuration, and NAT/STUN settings for VoIP connectivity.',
    'rest_NetworkFilters_ApiDescription' => 'Read-only access to network filters (firewall rules) for UI dropdown lists. Supports category-based filtering (SIP, IAX, AMI, API) and includes special localhost option. For creating/updating filters, use the Firewall API.',
    'rest_OffWorkTimes_ApiDescription' => 'Time-based routing conditions for handling calls outside business hours. Features include time range definitions (daily, weekly, date-specific), holiday scheduling, action routing (forward to extension, play audio), and priority-based rule evaluation.',
    'rest_OpenAPI_ApiDescription' => 'OpenAPI specification and documentation management for MikoPBX REST API. Provides access to API documentation, ACL rules, validation schemas, and metadata. Singleton resource pattern - only one specification exists. All endpoints require authentication for security.',
    'rest_OutboundRoutes_ApiDescription' => 'Outbound call routing management for directing calls to external providers. Features include number pattern matching (prefix-based), provider selection, priority-based route selection, digit manipulation, and trunk failover support.',
    'rest_Passkeys_ApiDescription' => 'WebAuthn passkey management and authentication for passwordless login. Supports FIDO2/WebAuthn standards for secure biometric and hardware key authentication. Provides registration flow for authenticated users and authentication flow for public access.',
    'rest_Passwords_ApiDescription' => 'Password management utilities for validation and generation. Features include password strength validation, secure password generation, dictionary attack checking, and batch operations for multiple passwords.',
    'rest_Providers_ApiDescription' => 'Comprehensive VoIP provider management for listing and monitoring both SIP and IAX providers. This read-only endpoint provides unified access to all provider types. For create/update/delete operations, use type-specific endpoints: /api/v3/sip-providers or /api/v3/iax-providers. Providers are identified by unique identifiers (PROV-XXX format) and can be filtered by type, status, or registration state. Supports real-time status monitoring, historical data retrieval, and statistics tracking.',
    'rest_Sip_ApiDescription' => 'SIP device status monitoring and statistics. Provides real-time status information for SIP endpoints, peers, and registry. Read-only monitoring interface - device configuration is managed via Extensions API.',
    'rest_SipProviders_ApiDescription' => 'Comprehensive SIP provider management for Session Initiation Protocol (SIP) trunking. SIP is the industry-standard VoIP protocol for voice and video communications. Features include provider registration, status monitoring, connection testing, and statistics tracking.',
    'rest_SoundFiles_ApiDescription' => 'Sound file management for IVR menus, MOH, announcements and system prompts. Supports upload, conversion, playback and CRUD operations for audio files. Handles multiple audio formats with automatic conversion to system-compatible formats.',
    'rest_Storage_ApiDescription' => 'Comprehensive storage and disk management for MikoPBX. This singleton resource provides access to storage configuration including disk selection, mount points, usage statistics, and file system operations. Manages call recording retention periods, monitors disk space utilization, and provides tools for formatting and mounting storage devices. Essential for system administrators managing storage capacity and data retention policies.',
    'rest_Sysinfo_ApiDescription' => 'System information and diagnostics singleton resource. Provides comprehensive details about hardware, network configuration, virtualization platform, and DMI data. Read-only interface for system monitoring and troubleshooting.',
    'rest_Syslog_ApiDescription' => 'System logs management and diagnostics tools. Provides access to system logs, log filtering, network packet capture, and archive generation. Essential for troubleshooting and system monitoring.',
    'rest_System_ApiDescription' => 'System-wide management singleton resource. Provides power management (reboot, shutdown), health monitoring (ping, checkAuth), datetime operations, language settings, audio conversion, system upgrades and factory reset.',
    'rest_TimeSettings_ApiDescription' => 'Comprehensive time and timezone management for MikoPBX. This singleton resource provides access to system time configuration including timezone selection, NTP server settings, and manual time adjustment. Essential for ensuring accurate call timestamps, scheduled tasks execution, and system log correlation. Supports automatic time synchronization via NTP or manual time setting for isolated networks.',
    'rest_UserPageTracker_ApiDescription' => 'User page activity tracking for admin interface. Records page views and departures to track which administrators are currently viewing which pages. Used for session management, activity monitoring, and preventing concurrent editing conflicts.',
    'rest_Users_ApiDescription' => 'User account management for admin interface access. Supports full CRUD operations plus custom methods for email availability checking. Users can authenticate to the admin interface and have personalized settings like language and avatar.',

];
