#!/bin/sh

if [ "$DNS1" -o "$DNS2" ] ; then
	sed -i -e '/.*# automatically added/d' /etc/resolv.conf
	(
	  echo "# automatically added by $0 during PPP connect ..."
	  [ "$DNS1" ] && echo "nameserver $DNS1 # automatically added"
	  [ "$DNS2" ] && echo "nameserver $DNS2 # automatically added"
	) >> /etc/resolv.conf
fi

