#!/usr/bin/php -f
<?php
/*
 * MikoPBX - free phone system for small business
 * Copyright © 2017-2023 Alexey Portnov and Nikolay Beketov
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with this program.
 * If not, see <https://www.gnu.org/licenses/>.
 */
namespace MikoPBX\Core\RootFS\etc\rc;
use MikoPBX\Core\System\ConsoleMenu;
use MikoPBX\Core\System\System;
require_once('Globals.php');

// STDIN watchdog: if controlling pty is hung up (SSH disconnect, console drop)
// the underlying CliMenu read-loop spins on EOF at 100% CPU. Periodically poll
// STDIN; on EOF/!isatty terminate cleanly so dropbear's child group can be reaped.
if (function_exists('pcntl_async_signals') && function_exists('pcntl_signal') && function_exists('pcntl_alarm')) {
    pcntl_async_signals(true);
    $stdinWatchdog = static function () use (&$stdinWatchdog): void {
        if (feof(STDIN) || @posix_isatty(STDIN) === false) {
            exit(0);
        }
        pcntl_signal(SIGALRM, $stdinWatchdog);
        pcntl_alarm(2);
    };
    pcntl_signal(SIGALRM, $stdinWatchdog);
    pcntl_signal(SIGHUP, static function (): void { exit(0); });
    pcntl_signal(SIGTERM, static function (): void { exit(0); });
    pcntl_alarm(2);
}

// Wait for system boot to complete before starting console menu.
// Console menu requires Redis and DB migrations to be ready.
$maxWait = 120; // seconds
$waited = 0;
while (System::isBooting() && $waited < $maxWait) {
    sleep(1);
    $waited++;
}

$cMenu = new ConsoleMenu();
$cMenu->start();