#!/usr/bin/php -f
<?php
/*
 * MikoPBX - free phone system for small business
 * Copyright © 2017-2023 Alexey Portnov and Nikolay Beketov
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with this program.
 * If not, see <https://www.gnu.org/licenses/>.
 */
namespace MikoPBX\Core\RootFS\etc\rc;
use MikoPBX\Core\System\Configs\RedisConf;
use MikoPBX\Core\System\ConsoleMenu;
require_once('Globals.php');

// Wait for Redis to be available before starting console menu.
// Console menu requires Redis for translations and settings cache.
if (!RedisConf::waitForReady(60)) {
    echo "Warning: Redis not available, starting menu anyway...\n";
}

$cMenu = new ConsoleMenu();
$cMenu->start();