#!/bin/sh
#
# MikoPBX - free phone system for small business
# Copyright © 2017-2023 Alexey Portnov and Nikolay Beketov
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <https://www.gnu.org/licenses/>.
#

PATH=/sbin:/bin:/usr/sbin:/usr/bin;
export PATH;

# Defence in depth: when dropbear/sshd closes the slave pty after a sudden
# disconnect, the kernel sends SIGHUP only to the session leader (this script).
# By default sh inherits SIG_IGN for SIGHUP from its parent, leaving the whole
# child chain (pbx_init → console_menu) orphaned. Explicitly trap and kill the
# entire process group so PHP children terminate too.
trap 'trap - HUP TERM; kill 0 2>/dev/null; exit 0' HUP TERM

/sbin/pbx_init;