#!/usr/bin/php -f
<?php
/*
 * MikoPBX - free phone system for small business
 * Copyright © 2017-2023 Alexey Portnov and Nikolay Beketov
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with this program.
 * If not, see <https://www.gnu.org/licenses/>.
 */

namespace MikoPBX\Core\RootFS\etc\rc;

use MikoPBX\Core\System\{Processes, Util, Network};

require_once('Globals.php');

/**
 * If running inside a Docker container, exit the script.
 */
if (Util::isDocker()) {
    exit(0);
}

/**
 * Get the action parameter from the command line arguments.
 * Default to an empty string if not provided.
 */
$action = $argv[1]??'';
if ('start' === $action) {
    $network = new Network();

    /**
     * Generate the resolv.conf file for DNS configuration.
     */
    $network->resolvConfGenerate();
    if (Util::isT2SdeLinux()) {
        /**
         * Configure the loopback interface for T2SDE Linux.
         */
        $network->loConfigure();
    }
    /**
     * Configure the LAN interfaces.
     */
    $network->lanConfigure();
} elseif ('stop' === $action) {
    if (Util::isSystemctl()) {
        /**
         * Stop networking using systemctl (systemd-based systems).
         */
        $systemctlPath = Util::which('systemctl');
        Processes::mwExec("{$systemctlPath} stop networking");
    } else {
        /**
         * Stop networking on T2SDE (non-systemd) systems.
         */
        $network      = new Network();
        $if_list      = $network->getInterfaces();
        $arr_commands = [];
        $ifconfigPath = Util::which('ifconfig');
        foreach ($if_list as $if_name => $data) {
            $arr_commands[] = "{$ifconfigPath} $if_name down";
        }

        /**
         * Execute the stop commands for each interface.
         */
        Processes::mwExecCommands($arr_commands, $out, 'net_stop');
    }
}