#!/usr/bin/php -f
<?php
/*
 * MikoPBX - free phone system for small business
 * Copyright © 2017-2023 Alexey Portnov and Nikolay Beketov
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with this program.
 * If not, see <https://www.gnu.org/licenses/>.
 */

use MikoPBX\Core\System\Udhcpc6;

require_once 'Globals.php';

/**
 * DHCPv6 client callback script for udhcpc6
 *
 * Called on DHCPv6 events: deconfig, bound, renew
 *
 * Receives environment variables from udhcpc6:
 * - interface: eth0
 * - ipv6: DHCPv6-assigned IPv6 address
 * - mask: Prefix length (usually 128 for single address, or delegated prefix length)
 * - dns: IPv6 DNS servers (space-separated)
 * - domain: Domain name
 */

/**
 * Get the action parameter from the command line arguments and convert it to lowercase.
 */
$action = strtolower(trim($argv[1]));

$udhcpc6Client = new Udhcpc6();
$udhcpc6Client->configure($action);
