#!/usr/bin/env bash
# Bootstraps the local S3-provider test stand:
#   - assigns a Garage layout (single-node, 1 GB capacity)
#   - creates a Garage bucket (mikopbx-test) and a key with full perms
#   - creates a MinIO bucket (mikopbx-test) using mc inside the container
#   - prints the credentials in a form the pytest tests can source
#
# Idempotent: safe to re-run.

set -euo pipefail

GARAGE=mikopbx-test-garage
MINIO=mikopbx-test-minio
BUCKET=mikopbx-test
KEY_NAME=mikopbx-key

# Generate the .env.s3-test file with random Garage tokens on first run.
# docker-compose loads it via env_file: so the values reach Garage as the
# GARAGE_RPC_SECRET and GARAGE_ADMIN_TOKEN environment variables. The
# file is gitignored.
SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
ENV_FILE="$SCRIPT_DIR/.env.s3-test"
if [ ! -f "$ENV_FILE" ]; then
    {
        echo "# Auto-generated by bootstrap-s3-providers.sh on $(date -u +%FT%TZ)."
        echo "# Throwaway test stand tokens — never reuse outside the local test stand."
        echo "# WARNING: deleting this file invalidates the existing Garage cluster"
        echo "# state in the garage_meta volume; run 'docker compose down -v' first."
        echo "GARAGE_RPC_SECRET=$(openssl rand -hex 32)"
        echo "GARAGE_ADMIN_TOKEN=$(openssl rand -hex 32)"
    } > "$ENV_FILE"
    chmod 600 "$ENV_FILE"
    echo "Generated $ENV_FILE — bringing the stand up so containers pick up the new tokens..."
    (cd "$SCRIPT_DIR" && docker compose -f docker-compose.s3-providers.yml up -d >/dev/null)
fi

if ! docker inspect "$GARAGE" >/dev/null 2>&1; then
    echo "Garage container '$GARAGE' is not running. Start the stand first:"
    echo "  docker compose -f docker-compose.s3-providers.yml up -d"
    exit 1
fi

# ---- Garage ----------------------------------------------------------------

# Wait until garage answers `status` (cluster up).
for _ in $(seq 1 30); do
    if docker exec "$GARAGE" /garage status >/dev/null 2>&1; then break; fi
    sleep 1
done

NODE_ID=$(docker exec "$GARAGE" /garage node id -q | cut -d@ -f1)

# Layout assign is needed only when the cluster has no role applied yet.
# `garage layout show` ALWAYS prints the "==== CURRENT CLUSTER LAYOUT ===="
# header (even with version 0 / no roles), so we detect "still empty" by
# the layout version line instead.
if docker exec "$GARAGE" /garage layout show 2>/dev/null | grep -qE "^Version:[[:space:]]+0\b"; then
    docker exec "$GARAGE" /garage layout assign -z dc1 -c 1G "$NODE_ID"
    docker exec "$GARAGE" /garage layout apply --version 1
fi

# Create the bucket if it does not exist (suppress duplicate-bucket errors).
docker exec "$GARAGE" /garage bucket create "$BUCKET" 2>/dev/null || true

# Create the key (or fetch it if it already exists) and grant permissions.
# `key info` redacts the secret without --show-secret, so a second run of
# this script would otherwise print the literal word "redacted" as the
# secret_key, causing pytest to hit SignatureDoesNotMatch.
KEY_INFO=$(docker exec "$GARAGE" /garage key info --show-secret "$KEY_NAME" 2>/dev/null \
    || docker exec "$GARAGE" /garage key create "$KEY_NAME")
docker exec "$GARAGE" /garage bucket allow \
    --read --write --owner "$BUCKET" --key "$KEY_NAME" >/dev/null

GARAGE_ACCESS_KEY=$(echo "$KEY_INFO" | awk '/Key ID:/ {print $3}')
GARAGE_SECRET_KEY=$(echo "$KEY_INFO" | awk '/Secret key:/ {print $3}')

# ---- MinIO -----------------------------------------------------------------

if docker inspect "$MINIO" >/dev/null 2>&1; then
    docker exec "$MINIO" \
        sh -c 'until mc alias set local http://localhost:9000 minioadmin minioadmin >/dev/null 2>&1; do sleep 1; done'
    docker exec "$MINIO" mc mb --ignore-existing "local/$BUCKET" >/dev/null

    MINIO_ACCESS_KEY=minioadmin
    MINIO_SECRET_KEY=minioadmin
fi

# ---- Output ----------------------------------------------------------------
# Printed as KEY=value lines; tests source this file via dotenv-like parser.

cat <<EOF
# Generated by tests/api/bootstrap-s3-providers.sh
GARAGE_ENDPOINT=http://mikopbx-test-garage:3900
GARAGE_REGION=garage
GARAGE_BUCKET=$BUCKET
GARAGE_ACCESS_KEY=$GARAGE_ACCESS_KEY
GARAGE_SECRET_KEY=$GARAGE_SECRET_KEY

MINIO_ENDPOINT=http://mikopbx-test-minio:9000
MINIO_REGION=us-east-1
MINIO_BUCKET=$BUCKET
MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY:-}
MINIO_SECRET_KEY=${MINIO_SECRET_KEY:-}
EOF
