#!/bin/sh

HOME=/;
PATH=/sbin:/bin:/usr/sbin:/usr/bin;
export HOME PATH;

# Создание каталогов и ссылок.
mkdir -p /dev/pts \
		 /dev/bus\
		 /tmp \
		 /ultmp \
		 /offload \
		 /cf/conf \
		 /var/etc \
		 /var/spool/cron \
		 /var/spool/cron/crontabs \
		 /var/cache/www/admin-cabinet/cache/volt \
		 /var/cache/www/back-end/cache/metadata/ \
		 /var/cache/www/back-end/cache/datacache/ \
		 /var/log/www/admin-cabinet/logs \
		 /var/lib/php/session;
		 		 
chown -R www:www /var/cache/www \
				 /var/log/www \
				 /var/lib/php/session;
chmod 777 /tmp				 
ln -s /offload/rootfs/usr /usr;

rm -rf /dev/null;
mknod /dev/null c 1 3;
mknod /dev/initctl p;

# Подключаем устройства.
/sbin/udevd --daemon;
/sbin/udevadm trigger;
/sbin/udevadm settle;

sleep 5;
mount -t devpts none /dev/pts;

ln -s /sys/bus/usb /dev/bus/usb

# Опции ядра linux
/sbin/sysctl -w kernel.printk="3 4 1 3" > /dev/null 2> /dev/null;
/sbin/sysctl -w net.ipv6.conf.all.disable_ipv6=1

/etc/rc/mountoffload;
/etc/rc/mountconfdir;