#!/usr/bin/php -f
<?php
 /**
  * Copyright © MIKO LLC - All Rights Reserved
  * Unauthorized copying of this file, via any medium is strictly prohibited
  * Proprietary and confidential
  * Written by Alexey Portnov, 5 2018
  */
namespace MikoPBX\Core\Rc;

use MikoPBX\Core\System\{
    Util,
    SystemLoader
};
require_once('globals_boot.php');
echo ' - Start /etc/rc/bootup_pbx ...'.PHP_EOL;

while (true){
     $pid = Util::getPidOfProcess('beanstalkd');
     if(empty($pid)){
         echo ' - Wait for start beanstalkd deamon...' .PHP_EOL;
         sleep(2);
     }else{
         echo ' - Start SystemLoader...'.PHP_EOL;
         $mikoPBX = new SystemLoader();
         $mikoPBX->startMikoPBX();
         break;
     }
}

