#!/usr/bin/php -f
<?php
/*
 * MikoPBX - free phone system for small business
 * Copyright (C) 2017-2020 Alexey Portnov and Nikolay Beketov
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with this program.
 * If not, see <https://www.gnu.org/licenses/>.
 */

namespace MikoPBX\Core\Rc;
use MikoPBX\Core\System\{Processes, Util, SystemLoader};
if('docker' === ($argv[1]??'')){
    define('START_DOCKER',1);
}
require_once('Globals.php');
Util::echoWithSyslog(' - Start /etc/rc/bootup ...'.PHP_EOL);
if(file_exists('/tmp/ejectcd')){
    sleep(15);
}

$mikoPBX = new SystemLoader();
Util::echoWithSyslog(' - Start SystemLoader\startSystem...'.PHP_EOL);
$result = $mikoPBX->startSystem();

if((true === $result) && ! file_exists('/offload/livecd') && ! Util::isDocker()) {
    Processes::mwExecBg('/etc/rc/bootup_pbx');
}