#!/bin/sh

PATH=/sbin:/bin
export PATH

# Подключаем библиотеку функций.
. /etc/rc/shell_functions.sh;

/bin/touch /tmp/freeoffload;

killprocess_by_name 'pdnsd' -9 0;

killprocess_by_name 'crond' -KILL 0;
killprocess_by_name 'nginx' -KILL 0;
killprocess_by_name 'monitord' -KILL 1;

killprocesses '/offload' -TERM 3;
killprocesses '/offload' -KILL 0;

echo " |   - unmounting /offload ...";
f_umount /offload;
echo " |   - unmounting /cf...";
f_umount /cf;

