#!/usr/bin/php -f
<?php
/*
 * MikoPBX - free phone system for small business
 * Copyright (C) 2017-2020 Alexey Portnov and Nikolay Beketov
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with this program.
 * If not, see <https://www.gnu.org/licenses/>.
 */

namespace MikoPBX\Core\Rc;

use MikoPBX\Core\System\{Processes, Util, Network};

require_once('Globals.php');

if (Util::isDocker()) {
    exit(0);
}
$action = $argv[1]??'';
if ('start' === $action) {
    $network = new Network();
    $network->resolvConfGenerate();
    $network->loConfigure();
    $network->lanConfigure();
} elseif ('stop' === $action) {
    if (Util::isSystemctl()) {
        $systemctlPath = Util::which('systemctl');
        Processes::mwExec("{$systemctlPath} stop networking");
    } else {
        $network      = new Network();
        $if_list      = $network->getInterfaces();
        $arr_commands = [];
        $ifconfigPath = Util::which('ifconfig');
        foreach ($if_list as $if_name => $data) {
            $arr_commands[] = "{$ifconfigPath} $if_name down";
        }
        Processes::mwExecCommands($arr_commands, $out, 'net_stop');
    }
}