#!/bin/sh

disk="${1}";
disk_name=$(basename $disk);
if [ ! -b "${disk}" ]; then
    echo " - ERROR block devise ${disk} not found";
    exit 1;
fi;

if [ -b "${disk}4" ]; then
    # System disk
    part='4';
else
    # Storage disk
    part='1';
fi;

tmp_dir='/storage/usbdisk1';
mkdir -p "$tmp_dir";
mount "${disk}${part}" "$tmp_dir";
if [ "$?" != "0" ]; then
    echo " - ERROR mount storage disk part ${part}...";
    rm -rf "$tmp_dir";
    exit 2;
fi;

total_byte=`busybox blockdev --getsize64 $disk`;
total=`expr $total_byte / 1024 / 1024`;
disk_size=`/bin/busybox df -P -m | /bin/busybox grep "${disk}${part}" | busybox head -n 1 | /bin/busybox awk  '{ print $2}'`;
umount "${disk}${part}";

delta=`expr $total - $disk_size`;
echo " - disk: '${disk}'";
echo " - total_size: ${total}Mb";
echo " - partition_size: ${disk_size}Mb";

if [ -b "${disk}4" ]; then
    echo " - is SYSTEM disk: '${disk}'";
    system_size=600;
    if [ "$delta" -le "$system_size" ]; then
        delta=0;
    else
        # Уменьшим на размер образа системы.
        delta=`expr $delta - $system_size`;
    fi;
fi;
echo " - delta: ${delta}Mb";
# portion - это процент * 100. В shell работаем только с целыми числами.
portion=`expr $delta \* 10000 / $total `;
if [ "$portion" -le "500" ]; then
    # Менять размер не будем, доля увеличения раздела не более 5 процентов.
    echo " - delta is less than five percent.";
    echo " - the partition size will not be changed.";
    sleep 1;
    exit 3;
fi;

is_mounted=$(mount | grep "$disk");
if [ "${is_mounted}x" != "x" ]; then
    echo ' - free storage...';
    /bin/freestorage;
fi;

echo " - delete part ${part} / add new part ${part}...";

if [ -b "${disk}4" ]; then
    /bin/freeupoffload;
    fdisk "$disk" > /dev/null 2> /dev/null << EOF
d
${part}
w
EOF
    /etc/rc/initial.storage.part.four create "$disk";
    sleep 2;

    need_reboot=1;
else
    fdisk "$disk" > /dev/null 2> /dev/null << EOF
d
${part}
n
p
${part}


w
EOF
fi;

/sbin/blockdev --rereadpt "${disk}" > /dev/null 2>&1;
sleep 2;
fs_type=$(/sbin/blkid -ofull "${disk}${part}");
if [ "${fs_type}x" != "x" ]; then
    echo " - e2fsck ${disk} part ${part}...";
    e2fsck -f -p "${disk}${part}";
    sleep 2;
    echo " - resize2fs ${disk} part ${part}..."
    resize2fs "${disk}${part}";
    sleep 2;
else
    echo " - error blkid $?"
fi;

if [ "${need_reboot}x" != "x" ]; then
    touch /tmp/ejectcd;
    /sbin/mikopbx_reboot;
fi;

