{# Minimal container for JavaScript-generated content #}
<div id="firewall-content" class="ui loading basic segment" style="min-height: 200px;">
    {# All content will be generated by JavaScript from REST API data #}
</div>