location ^~ /avatars/ {
    alias /storage/usbdisk1/mikopbx/media/avatars/;
    access_log off;
    log_not_found off;
    expires 7d;
    error_page 404 = /admin-cabinet/assets/img/unknownPerson.jpg;
}
