
location = /pbxcore/api/nchan/auth {
    # The authentication check will always fail, and a notification will be written to syslog.
    default_type 'text/plain';
    content_by_lua_file /etc/nginx/mikopbx/lua/fail-auth.lua;
    keepalive_timeout 0;
}

location ~ /pbxcore/api/nchan/sub/(.*)$ {
    nchan_subscriber;
    nchan_channel_id "$1";
    nchan_channel_id_split_delimiter ",";

    nchan_subscribe_request /internal/subscriber/connect;
    nchan_unsubscribe_request /internal/subscriber/disconnect;
 
    more_clear_headers 'Access-Control-Allow-Credentials';
    add_header 'X-Access-Control-Allow-Origin' '*';
    more_clear_headers 'Server';

    access_by_lua_file /etc/nginx/mikopbx/lua/access-nchan.lua;
}

# Add these internal locations to handle subscriptions and unsubscriptions
location = /internal/subscriber/connect {
    internal;
    proxy_pass http://api_backend/pbxcore/api/nchan/subscriber/connect;
    proxy_set_header X-Subscriber-Type $nchan_subscriber_type;
    proxy_set_header X-Channel-Id $nchan_channel_id;
    proxy_set_header X-Original-URI $request_uri;
}

location = /internal/subscriber/disconnect {
    internal;
    proxy_pass http://api_backend/pbxcore/api/nchan/subscriber/disconnect;
    proxy_ignore_client_abort on;  # IMPORTANT: Without this, some disconnection events may be missed
    proxy_set_header X-Subscriber-Type $nchan_subscriber_type;
    proxy_set_header X-Channel-Id $nchan_channel_id;
    proxy_set_header X-Original-URI $request_uri;
}

location ~ /pbxcore/api/nchan/pub/(.*)$ {
    nchan_publisher;
    allow  127.0.0.1;
    nchan_channel_id "$1";
    nchan_message_buffer_length 50;
    nchan_message_timeout 10s;
}