location = /favicon.ico {
    alias /usr/www/sites/admin-cabinet/favicon.ico;
    access_log off;
    expires 30d;
}
location ~ /\.ht {
    deny all;
}
location ~* ^.+\.(jpg|jpeg|gif|png|ico|css|ico|js|map|woff2)$ {
    access_log off;
    expires 3d;
}