#!/bin/sh
#
# MikoPBX - free phone system for small business
# Copyright (C) 2017-2020 Alexey Portnov and Nikolay Beketov
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <https://www.gnu.org/licenses/>.
#

HOME=/;
PATH=/sbin:/bin:/usr/sbin:/usr/bin;
export HOME PATH;

ln -s /bin/busybox /sbin/init;
# Монтирование.
mount -t devtmpfs  -o mode=0755,nosuid devtmpfs /dev
mount -t proc      -o nosuid,noexec,nodev proc  /proc;
mount -t sysfs     -o nosuid,noexec,nodev sysfs /sys;
mount -t tmpfs     -o size=90% tmpfs            /mnt;

# Переключение root.
if tar -C / --exclude=mnt --exclude="./proc/*" --exclude="./sys/*" -cf - . | tar -C /mnt/ -xf - ; then
	resFileInitTab='/mnt/etc/inittab';
	mv /mnt/etc/inittab_base "$resFileInitTab";

  devises="$(/bin/ls /dev/ttyS* 2> /dev/null)";
  for dev in $devises; do
    serialInfo="$(/bin/busybox setserial -g "$dev" 2> /dev/null)";
    if [ "${serialInfo}x" = 'x' ]; then
      continue;
    fi;
    echo "$serialInfo" | /bin/busybox grep unknown > /dev/null 2> /dev/null;
    resultSetSerial="$?";

    if [ ! "$resultSetSerial" = '0' ]; then
       # Device ttyS found
       devName="$(/bin/busybox basename "$dev")";
       echo " - Device $dev name - $devName";
       echo >> "$resFileInitTab";
       echo "::respawn:/sbin/agetty -a root -h -t 60 $devName 9600 vt102" >> "$resFileInitTab"
    fi;
  done

  sleep 5;
	exec /sbin/switch_root /mnt /sbin/init "$@";
fi