#!/bin/sh

HOME=/;
PATH=/sbin:/bin:/usr/sbin:/usr/bin;
export HOME PATH;

ln -s /bin/busybox /sbin/init;
# Монтирование.
mount -t proc   none /proc;
mount -t sysfs  none /sys;
mount -t tmpfs  none /dev -o mode=755;

# switch_root
mount -t tmpfs -o size=90% tmpfs /mnt;
if tar -C / --exclude=mnt --exclude="./proc/*" --exclude="./sys/*" -cf - . | tar -C /mnt/ -xf - ; then
	mkdir -p /mnt;
	mv /mnt/etc/inittab_2 /mnt/etc/inittab
	exec /sbin/switch_root /mnt /sbin/init "$@";
fi