#!/bin/sh
#
# MikoPBX - free phone system for small business
# Copyright (C) 2017-2020 Alexey Portnov and Nikolay Beketov
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <https://www.gnu.org/licenses/>.
#

HOME=/;
PATH=/sbin:/bin:/usr/sbin:/usr/bin;
export HOME PATH;

ln -s /bin/busybox /sbin/init;
# Монтирование.
uname -a | /bin/busybox grep ' 4\.10'; resultUname=$?
if [ '1' = "$resultUname" ]; then
	fsType='devtmpfs';
else
	fsType='tmpfs';
fi;
mount -t "$fsType" -o mode=0755,nosuid devtmpfs /dev
mount -t proc      -o nosuid,noexec,nodev proc  /proc;
mount -t sysfs     -o nosuid,noexec,nodev sysfs /sys;
mount -t tmpfs     -o size=90% tmpfs            /mnt;

# Переключение root.
if tar -C / --exclude=mnt --exclude="./proc/*" --exclude="./sys/*" -cf - . | tar -C /mnt/ -xf - ; then
	mv /mnt/etc/inittab_2 /mnt/etc/inittab
	exec /sbin/switch_root /mnt /sbin/init "$@";
fi