#!/usr/bin/php -f
<?php
/**
 * Copyright © MIKO LLC - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 * Written by Alexey Portnov, 5 2018
 */

require_once("globals.php");
while (true){
    $pid = Util::get_pid_process('beanstalkd');
    if(empty($pid)){
        sleep(2);
    }else{
        $g['booting'] = TRUE;
        Mikopbx\Main::bootup_pbx();
        $g['booting'] = FALSE;
        break;
    }
}

