#!/bin/sh

CFDEVICE=`cat /var/etc/cfdevice`;

case $1 in
enable)
	#/sbin/mdmfs -s 20m md1 /ultmp > /dev/null 2>&1
	;;
	
recover_upgrade)
	
	# $2 firmware image
	# $3 device

	# get out of /usr/www
	cd /;
	sleep 5;
	exec </dev/console >/dev/console 2>/dev/console;

	echo;
	echo "Firmware upgrade in progress...";
	echo " | - backing up configuration...";
	mkdir -p /tmp/configbak;

    img_file="$2";
    if [ -f /offload/livecd ]; then
	    cp -p /conf.recover/conf/* /tmp/configbak;
        echo " | - unmounting /conf.recover...";
        /bin/umount -f /conf.recover;
    else
	    cp -R /cf/conf/* /tmp/configbak;
	    # Перемещаем img файл в /tmp. Storage будет отмонтирован.
	    tmp_img=$(basename "$2");
	    img_file="/tmp/${tmp_img}";
	    mv "$2" "${img_file}";

	    /etc/rc/freestorage;
	    /etc/rc/freeupoffload;
    fi

	echo " | - installing image..."
	if [ -r "${img_file}" ]; then
		/bin/gunzip -c "${img_file}" | dd of=$3 bs=512 > /dev/null 2>&1;
        /etc/rc/initial.storage.part.four create $3;
        echo " | - disk part four result ${?}...";
	fi
	/sbin/blockdev --rereadpt $3 > /dev/null 2>&1;
	sleep 3;

	# Фиксируем флаг необходимости очистки кэш web.
	touch /tmp/configbak/need_clean_cashe_www;
    if [ -f /offload/livecd ]; then
        echo " | - re-mounting /conf.recover read/write...";
        /bin/mount -w -o noatime ${3}3 /conf.recover;
    	rm -f /conf.recover/conf/*;
        echo " | - restoring configuration";
        cp -p /tmp/configbak/* /conf.recover/conf/;
        touch /tmp/ejectcd;
    else
        /bin/mount -w -o noatime ${3}3 /cf/;
	    cp /tmp/configbak/* /cf/conf/;
        rm -rf "${img_file}";
    fi

	echo " | - rebooting system...";
	/etc/rc/reboot;
	;;

esac
