#!/bin/sh
while : ; do
    if [ -f /tmp/ejectcd ]; then
        # Это установка системы. Меню необходимо отключить.
        sleep 20;
    fi

    # Проверим, возможно требуется запустить shell.
    if [ -f /tmp/start_sh ]; then
        clear;
        rm -rf /tmp/start_sh;
        /bin/sh;
    fi

    # Убедимся, что раздел смонтирован.
    if [ ! -f /tmp/freeoffload ]; then
        clear;
        # Консольное меню зависит от /offload раздела.
        /etc/rc/console_menu 2>/dev/null;
        if [ $? -gt 0 ]; then
            /bin/sh;
        fi;
    else
        sleep 5;
    fi
done

