#!/bin/sh

/etc/rc/freestorage;
/etc/rc/freeupoffload;

if [ -f /tmp/ejectcd ]; then
    # Попробуем изъять диск.
    cddev=$(/sbin/sysctl -n dev.cdrom.info | /bin/busybox grep "drive name" | /bin/busybox cut -f 3)
    echo "Eject CD from drive ${cddev}...";
    /bin/busybox eject "/dev/${cddev}" 2>&1 > /dev/null;

else
    sleep 3;
fi

/sbin/reboot
