<?php

namespace MikoPBX\Core\Workers\Libs\WorkerModelsEvents\Actions;

use MikoPBX\Common\Models\PbxExtensionModules;
use MikoPBX\Common\Providers\ModulesDBConnectionsProvider;
use MikoPBX\Common\Providers\PBXConfModulesProvider;
use MikoPBX\Core\Asterisk\Configs\AsteriskConfigInterface;
use MikoPBX\Core\System\Processes;
use MikoPBX\Core\System\System;
use MikoPBX\Core\Workers\Cron\WorkerSafeScriptsCore;
use MikoPBX\Core\Workers\WorkerModelsEvents;
use MikoPBX\PBXCoreREST\Workers\WorkerApiCommands;
use MikoPBX\Modules\Cache\ModulesStateCache;
use MikoPBX\Modules\Config\ConfigClass;
use MikoPBX\Modules\Config\SystemConfigInterface;
use MikoPBX\Core\System\SystemMessages;

/**
 * Handles actions to reload module state when PBX extensions or module settings change.
 */
class ReloadModuleStateAction implements ReloadActionInterface
{
    public const string MODULE_SETTINGS_KEY = 'MODULE_SETTINGS_DATA';

    // Set by the install pipeline to force a module-aware worker refresh that
    // BYPASSES the enabled-module-set hash gate. An install/update replaces the
    // module code on disk, but the state hash is built from the module set and
    // version only ({@see ModulesStateCache::calculateCurrentStateHash()}), so a
    // same-version reinstall leaves the hash unchanged and the gate would skip the
    // restart — leaving WorkerModelsEvents running the old classes. This key forces
    // the restart regardless of the hash.
    public const string FORCE_REFRESH_KEY = 'FORCE_MODULE_REFRESH';

    /**
     * Executes the action to reload module state based on provided parameters.
     *
     * @param array $parameters An array of parameters that may include module settings.
     * @return void
     */
    public function execute(array $parameters = []): void
    {
        foreach ($parameters as $record) {
            if (array_key_exists(self::FORCE_REFRESH_KEY, $record)) {
                $this->forceModuleAwareRefresh();
            } elseif (!array_key_exists(self::MODULE_SETTINGS_KEY, $record)) {
                $this->planTheActionForFutureCycle($record);
            } else {
                $this->executeReloder($record[self::MODULE_SETTINGS_KEY]);
            }
        }
    }

    /**
     * Unconditionally refreshes the module-aware workers after an install/update.
     *
     * Called on the install pipeline's explicit request (see FORCE_REFRESH_KEY),
     * this bypasses the hash gate that {@see self::executeReloder()} applies: the
     * code on disk changed even when the enabled-module set and version did not, so
     * the caches are rebuilt, WorkerModelsEvents (which keeps module classes in
     * memory) is flagged to self-restart, and the Asterisk configs a module may
     * extend are regenerated by the fresh instance — reflecting the new code, not
     * the stale in-memory copy. Unlike restartModuleAwareWorkers(), this heavy path
     * is reserved for install/update, where the on-disk code actually changed.
     *
     * @return void
     */
    private function forceModuleAwareRefresh(): void
    {
        $this->recreateModuleProviders();

        // Keep the baseline in sync so the next genuine state change is detected.
        (new ModulesStateCache())->updateCachedState();

        SystemMessages::sysLogMsg(
            __CLASS__,
            'Forced module-aware worker refresh after module install/update (hash gate bypassed)',
            LOG_NOTICE
        );

        // Soft-restart the API worker and the supervisor (module set / classes).
        $this->restartModuleAwareWorkers();

        // Regenerate the Asterisk configs a module may extend via its hooks. These
        // are published as jobs and consumed by the fresh WorkerModelsEvents after
        // the self-restart below, so the dialplan/pjsip/features reflect the new
        // module code. Repeated empty-parameter jobs coalesce by hash, so no storm.
        // Publish BEFORE raising the self-restart flag: if a publish throws (e.g. a
        // transient Beanstalk outage), the flag stays cleared, so this action is not
        // kept in the backlog and replayed — which would loop the restart until the
        // queue recovers.
        WorkerModelsEvents::invokeAction(ReloadDialplanAction::class, [], 50);
        WorkerModelsEvents::invokeAction(ReloadPJSIPAction::class, [], 50);
        WorkerModelsEvents::invokeAction(ReloadFeaturesAction::class, [], 50);

        // WorkerModelsEvents is long-lived and loaded the old module classes once;
        // it cannot be soft-restarted from here (this action runs INSIDE it), so
        // raise a flag its reload loop checks right after this action to exit cleanly
        // and let the fresh instance replay the queued reloads with the new code.
        // See WorkerModelsEvents::$requestSelfRestart.
        WorkerModelsEvents::$requestSelfRestart = true;
    }

    /**
     * Rebuilds the per-process module caches so newly enabled/installed module
     * classes and DB connections are visible to this action's work.
     *
     * @return void
     */
    private function recreateModuleProviders(): void
    {
        PBXConfModulesProvider::recreateModulesProvider();
        ModulesDBConnectionsProvider::recreateModulesDBConnections();
    }

    /**
     * Performs the actual reloading of the module based on its configuration.
     *
     * @param array $moduleRecord Module configuration data.
     * @return void
     */
    private function executeReloder(array $moduleRecord): void
    {
        // Recreate the module providers / DB connections for this process
        $this->recreateModuleProviders();

        // Hook module methods if they change system configs
        // Only process module config if moduleRecord contains data (not a deletion)
        if (!empty($moduleRecord['uniqid'])) {
            $className = str_replace('Module', '', $moduleRecord['uniqid']);
            $configClassName = "Modules\\{$moduleRecord['uniqid']}\\Lib\\{$className}Conf";
            if (class_exists($configClassName)) {
                $configClassObj = new $configClassName();
                $this->handleModuleConfigChanges($configClassObj, $moduleRecord);
            }
        }

        // Check if modules state has changed before refreshing worker supervision
        $modulesStateCache = new ModulesStateCache();

        // Get current and cached hashes for comparison
        $cachedHash = $modulesStateCache->getCachedStateHash();
        $currentHash = $modulesStateCache->calculateCurrentStateHash();

        // A missing baseline (null) is ambiguous and must NOT be treated as
        // "no change". The baseline lives in the volatile ManagedCache (Redis
        // DB 4: 24h TTL, wiped by any cache-clear/FLUSHDB or a Redis restart),
        // so it is absent far more often than just on first boot. Two cases:
        //   - genuine first-boot initialization: the system is still coming up
        //     and the workers are (re)spawned by the boot sequence anyway, so a
        //     restart here would only add a needless storm — seed and return.
        //   - baseline lost at runtime: a real module install/enable/disable is
        //     in flight. We cannot prove the module set is unchanged, so the API
        //     workers (which cache PBXConfModulesProvider) and the supervisor
        //     MUST be refreshed. Skipping it is the bug where a freshly installed
        //     module's API classes / post-installation are never picked up until
        //     some later unrelated state change happens to hit a populated cache.
        if ($cachedHash === null) {
            $modulesStateCache->updateCachedState();

            if (System::isBooting()) {
                SystemMessages::sysLogMsg(
                    __CLASS__,
                    'Initializing modules state cache during boot, skipping worker supervisor refresh',
                    LOG_INFO
                );
                return;
            }

            SystemMessages::sysLogMsg(
                __CLASS__,
                'Modules state cache was empty at runtime (previous state unknown), '
                . 'refreshing worker supervisor to avoid serving a stale module set',
                LOG_INFO
            );
            $this->restartModuleAwareWorkers();
            return;
        }

        // Check if state actually changed
        if ($cachedHash !== $currentHash) {
            SystemMessages::sysLogMsg(
                __CLASS__,
                sprintf(
                    'Modules state has changed (old: %s, new: %s), refreshing worker supervisor',
                    $cachedHash,
                    $currentHash
                ),
                LOG_INFO
            );

            // Update cache with new state
            $modulesStateCache->updateCachedState();
            $this->restartModuleAwareWorkers();
        } else {
            SystemMessages::sysLogMsg(
                __CLASS__,
                'Modules state has not changed, skipping worker supervisor refresh',
                LOG_DEBUG
            );
        }
    }

    /**
     * Soft-restarts the workers that keep the enabled-module set in memory.
     *
     * API workers hold PBXConfModulesProvider for their whole lifetime, so they
     * must be refreshed when the enabled module set changes. The supervisor also
     * needs a refresh to start/stop workers registered by newly enabled/disabled
     * modules. A soft restart lets each worker finish its current job first.
     *
     * This runs on every enabled-module-set change (enable/disable/delete) as well
     * as on install (via {@see self::forceModuleAwareRefresh()}). It intentionally
     * does NOT bounce WorkerModelsEvents or regenerate Asterisk configs — that is
     * only needed when the module CODE on disk changed (install/update), so it lives
     * in forceModuleAwareRefresh() and must not be added here.
     *
     * @return void
     */
    private function restartModuleAwareWorkers(): void
    {
        Processes::processPHPWorker(
            WorkerApiCommands::class,
            'start',
            'soft-restart'
        );
        Processes::processPHPWorker(
            WorkerSafeScriptsCore::class,
            'start',
            'soft-restart'
        );
    }

    /**
     * Plans the action for a future cycle if the module settings are not immediately available.
     *
     * @param array $moduleRecord Partial module configuration data.
     * @return void
     */
    private function planTheActionForFutureCycle(array $moduleRecord): void
    {
        // Check if the module ID was presented
        if (empty($moduleRecord['recordId'])) {
            return;
        }

        // Find the module settings record
        $moduleSettings = PbxExtensionModules::findFirstById($moduleRecord['recordId']);
        if ($moduleSettings !== null) {
            // Invoke the action for the PBX module state with the module settings data
            $moduleRecord[self::MODULE_SETTINGS_KEY] = $moduleSettings->toArray();
            WorkerModelsEvents::invokeAction(ReloadModuleStateAction::class, $moduleRecord, 50);
        } elseif ($moduleRecord['action'] === 'afterDelete') {
            // Module was deleted, we need to check if state changed and restart workers
            SystemMessages::sysLogMsg(
                __CLASS__,
                "Module with ID {$moduleRecord['recordId']} was deleted, checking state change",
                LOG_INFO
            );

            // Execute reload directly without module data
            $this->executeReloder([]);
        }
    }

    /**
     * Handles module configuration changes and applies necessary system configuration reloads.
     *
     * @param ConfigClass $configClassObj The module configuration class object.
     * @param array $moduleRecord Module configuration data.
     * @return void
     */
    public function handleModuleConfigChanges(ConfigClass $configClassObj, array $moduleRecord): void
    {
        // Reconfigure fail2ban and restart iptables
        if (
            method_exists($configClassObj, SystemConfigInterface::GENERATE_FAIL2BAN_JAILS)
            && !empty(call_user_func([$configClassObj, SystemConfigInterface::GENERATE_FAIL2BAN_JAILS]))
        ) {
            WorkerModelsEvents::invokeAction(ReloadFail2BanConfAction::class, [], 50);
        }

        // Refresh Nginx conf if the module has any locations or server blocks
        $needsNginxReload = false;
        if (
            method_exists($configClassObj, SystemConfigInterface::CREATE_NGINX_LOCATIONS)
            && !empty(call_user_func([$configClassObj, SystemConfigInterface::CREATE_NGINX_LOCATIONS]))
        ) {
            $needsNginxReload = true;
        }
        if (
            method_exists($configClassObj, SystemConfigInterface::CREATE_NGINX_SERVERS)
            && !empty(call_user_func([$configClassObj, SystemConfigInterface::CREATE_NGINX_SERVERS]))
        ) {
            $needsNginxReload = true;
        }
        if ($needsNginxReload) {
            WorkerModelsEvents::invokeAction(ReloadNginxConfAction::class, [], 50);
        }

        // Refresh crontab rules if module has any for it
        if (method_exists($configClassObj, SystemConfigInterface::CREATE_CRON_TASKS)) {
            $tasks = [];
            call_user_func_array([$configClassObj, SystemConfigInterface::CREATE_CRON_TASKS], [&$tasks]);
            if (!empty($tasks)) {
                WorkerModelsEvents::invokeAction(ReloadCrondAction::class, [], 50);
            }
        }

        // Reconfigure asterisk manager interface
        if (
            method_exists($configClassObj, AsteriskConfigInterface::GENERATE_MANAGER_CONF)
            && !empty(call_user_func([$configClassObj, AsteriskConfigInterface::GENERATE_MANAGER_CONF]))
        ) {
            WorkerModelsEvents::invokeAction(ReloadManagerAction::class, [], 50);
        }

        // Lifecycle hooks are owned by PbxExtensionState. The model event that
        // reaches this action is a consequence of that state transition, so
        // invoking AFTER hooks here would repeat module side effects.
    }
}
